mod external_kind;
mod function_body;
mod global;
mod instructions;
mod memory;
mod table;
mod value_type;
pub use external_kind::ExternalKind;
pub use function_body::FnBody;
pub use global::GlobalDescriptor;
pub use global::GlobalValue;
pub use instructions::Instruction;
pub use memory::Memory;
pub use memory::ResizableLimits;
pub use table::Table;
pub use value_type::ValType;
