name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      runs-on: [ubuntu-latest, windows-latest, macosx-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose --all-targets

  release_build:
    strategy:
      runs-on: [ubuntu-latest, windows-latest, macosx-latest]

    steps:
    - uses: actions/checkout@v3
    - name: build release
      run: cargo build --release --all-targets